// Code generated by Slice Machine. DO NOT EDIT.

import HeroSlice from './HeroSlice';
import ImageTextSlice from './ImageTextSlice';
import NavigationItem from './NavigationItem';

export {
	HeroSlice,
	ImageTextSlice,
	NavigationItem,
};

export const components = {
	hero_slice: HeroSlice,
	image_text_slice: ImageTextSlice,
	navigation_item: NavigationItem,
};
