// Code generated by Slice Machine. DO NOT EDIT.

import ASliceWithASuperLongNam from './ASliceWithASuperLongNam';
import HeroSlice from './HeroSlice';
import ImageTextSlice from './ImageTextSlice';
import NavigationItem from './NavigationItem';

export {
	ASliceWithASuperLongNam,
	HeroSlice,
	ImageTextSlice,
	NavigationItem,
};

export const components = {
	a_slice_with_a_super_long_name_that_will_display: ASliceWithASuperLongNam,
	hero_slice: HeroSlice,
	image_text_slice: ImageTextSlice,
	navigation_item: NavigationItem,
};
